---
- name: Include homelab-specific variables
  include_vars: "homelab.yml"
- name: Update homelab-specific variables # noqa ignore-errors
  set_fact:
    postgresql_users: "{{ postgresql_users + postgresql_homelab_users }}"
    postgresql_hba_entries: "{{ postgresql_hba_entries + postgresql_homelab_hba }}"
  # continue on if our users can't be added for sone reason (for example, if vault is unreachable)
  retries: 3
  delay: 5
  ignore_errors: true

# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml
- include_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: users_props.yml

- include: homelab.yml
